### ISSUE TITLE
LICENSE ?

### ISSUE THREAD

**Issue by NikkyAI** [ikayzo/SDL#2]
what is the state of this project and in case it is abandoned..
what is the license?
am i allowed to fork it and use it in GPL/FOSS context ?

edit: bump @jwang @mleuck @micjamking @dleuck

**Comment by skyem123** [comment]
If possible, I'd suggest either ISC licence or LGPL licence so that people can use it in non GPL projects.

**Comment by NikkyAI** [comment]
actually i am totally blind,i did not see the mention of the license in the head of every file, sorry
closing it

**Comment by skyem123** [comment]
._.   oops.
